---
- name: Setup apache web server
  hosts: debian_nodes
  become: true

  tasks:
    - name: Install apache server
      apt:
        name: apache2
        state: present
        update-cache: true

    - name: Start and enable apache2 service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Deploy a basic html page
      copy:
        content: "<h1>Hey peeps! Apache is running...</h1>"
        dest: /var/www/html/index.html
        mode: '0644'
