---
- name: Create a new sudo user
  hosts: debian_nodes
  become: true

  vars:
    new_username: webadmin
    new_password_hash: "$6$IKc300HPf8le14Br$t.T5C1nowP5PPrFvygKMJw7KDspzboygnvp1vAtjvYszEvW9Hg/MbKUOMlsUpf8GR4aBxKXtvsv30yUO7wi3t0"

  tasks:
    - name: create the user
      user:
        name: "{{ new_username }}"
        password: "{{ new_password_hash }}"
        shell: /bin/bash
        append: yes
        create_home: yes
        groups: sudo
